/*eslint-disable camelcase*/
/*eslint quotes: [2, "double"]*/
/*global Skype*/

// For messages that have different wording for business, use the same key as the consumer counterpart but with a "_4b" suffix.
// Then use the knockout binding "businessAwareL10n" instead of "l10n" in the UI view for messages that have business variants.
// With the business aware binding, _4b messages will be automatically used if the useBusinessWording feature flag is active.
// Example:
//  newbee_text_cta: "Find your friends by entering their name or email in the Search Skype field.",
//  newbee_text_cta_4b: "Find your co-workers by entering their name in the Search field.",

Skype && Skype.WebExperience && Skype.WebExperience.setTranslations({

    splashScreen_text_logo_4b: "Skype Empresarial",
    splashScreen_text_loading: "Cargando...",
    splashScreen_text_signingIn: "Iniciando sesión...",
    splashScreen_text_signingIn_wac: "Uniéndose al chat...",
    splashScreen_text_loading_skype: "Cargando Skype",
    splashScreen_text_loading_skype_4b: "Cargando Skype Empresarial",
    splashScreen_text_signing_into_skype: "Iniciando sesión en Skype",
    splashScreen_text_signing_into_skype_4b: "Iniciando sesión en Skype Empresarial",
    splashScreen_signedOut_title: "Inicia sesión para comenzar.",
    splashScreen_signedOut_title_wac: "Únase al chat para empezar.",
    splashScreen_disconnected_title: "La conexión ha finalizado.",
    splashScreen_disconnected_description: "Intenta iniciar sesión de nuevo o bien actualiza la página.",
    splashScreen_disconnected_description_wac: "Intente unirse al chat de nuevo o actualice la página.",
    splashScreen_signInFailed_title: "No se puede iniciar sesión.",
    splashScreen_signInFailed_title_wac: "No hemos podido unirle al chat.",
    splashScreen_signInFailed_title_security_validation: "Haga llamadas de voz y video con Skype para Web.",
    splashScreen_signInFailed_description: "Intente iniciar sesión de nuevo o actualice la página.",
    splashScreen_signInFailed_description_wac: "Intente unirse al chat de nuevo o actualice la página.",
    splashScreen_signInFailed_description_exceeded_endpoints: "Skype ha superado el número de extremos permitidos.",
    splashScreen_signInFailed_description_age_restriction: "No puede usar Skype por restricciones de edad.",
    splashScreen_signInFailed_aad_description: "Intentar iniciar sesión de nuevo o actualice la página.",
    splashScreen_learn_more: "Más información",

    splashScreen_signIn_button: "Iniciar sesión",
    splashScreen_signIn_button_wac: "Unirse al chat",
    splashScreen_signInExternal_button: "Iniciar sesión con una cuenta de Microsoft",

    splashScreen_signInExternal_title: "Intentando iniciar sesión.",
    splashScreen_signInExternal_description: "Escriba su cuenta y su contraseña cuando se le solicite.",

    unsupportedBrowser_title: "Actualiza tu explorador para comenzar a usar Skype.",

    skypeUnavailable_title: "Actualmente, estamos experimentando problemas con el servidor. Skype está trabajando en los problemas y volverá a estar disponible enseguida.",

    aggressiveLinking_intro_title: "Saluda en Outlook",
    aggressiveLinking_intro_description: "Ahora puedes llamar y chatear con tus contactos de Outlook desde tu bandeja de entrada y totalmente gratis.",
    aggressiveLinking_intro_continue: "Continuar",
    aggressiveLinking_intro_signin: "¿Ya usas Skype? {link_start}Inicia sesión{link_end}",
    aggressiveLinking_intro_legal: "Si continúas, estás de acuerdo con los {link_tou_start}Términos de uso{link_tou_end} y la {link_privacy_start}Política de privacidad{link_privacy_end} de Skype.",

    one_account_link: "¿Ya usa Skype? {link_start}Más información{link_end}",

    input_placeholder_searchSkype: "Buscar en Skype",
    input_searchSkype_ariaLabel: "Búsqueda de conversación. Escribe un nombre de grupo o de contacto.",
    input_searchSkype_ariaLabel_4b: "Busque conversaciones. Escriba el nombre del contacto.",
    input_searchSkypeDirectory_ariaLabel: "Buscar en directorio de Skype",
    clear_search_input_label: "Borrar búsqueda",

    button_text_newChat: "Nueva conversación",
    button_text_new: "Nueva conversación",
    button_text_dialpad: "Llamar",
    input_text_skypeOut: "Escribe un nombre o un número",
    input_text_skypeOut_short: "Introducir número",
    clear_phonenumber_input_label: "Borrar número de teléfono",

    select_placeholder_skypeOut: "Elegir el país o la región",
    label_text_participant: "{count} participante",
    label_text_participant_few: "{count} participantes",
    label_text_participant_many: "{count} participantes",
    area_text_insertText: "Escribe un mensaje",
    area_text_insertTextWithCommands: "Escriba aquí un mensaje o {helpCommand} para acceder a la lista de comandos",
    area_text_agent_insertText: "No puede responder en este momento",
    area_text_insertTextNonMember: "Has salido de este grupo.",
    label_text_insertText_oneToOne: "Entrada de chat, conversación {displayName}",
    label_text_insertText_group: "Entrada de chat, conversación con {displayName}, {participantsCount} participantes",
    label_text_conversationsLoading: "Cargando conversaciones recientes...",
    label_text_conversationsLoadNone: "No hay conversaciones recientes",
    label_text_currentCallHeading: "Llamada en curso",
    label_text_openConversation: "Abrir conversación con {displayName}",
    label_text_from: "De: ",
    label_text_clearedText: "Área de texto limpiada",

    today: "hoy",
    yesterday: "ayer",
    olderThanAWeek: "más de una semana",

    duration_days: "{count} día",
    duration_days_few: "{count} días",
    duration_days_many: "{count} días",
    duration_hours: "{count} hora",
    duration_hours_few: "{count} horas",
    duration_hours_many: "{count} horas",
    duration_minutes: "{count} minuto",
    duration_minutes_few: "{count} minutos",
    duration_minutes_many: "{count} minutos",
    duration_moment: "momento",

    content_search_conversation_title_days: "Hace {count} día en <b>{conversationTitle}</b>",
    content_search_conversation_title_days_few: "Hace {count} días en <b>{conversationTitle}</b>",
    content_search_conversation_title_days_many: "Hace {count} días en <b>{conversationTitle}</b>",
    content_search_conversation_title_hours: "Hace {count} hora en <b>{conversationTitle}</b>",
    content_search_conversation_title_hours_few: "Hace {count} horas en <b>{conversationTitle}</b>",
    content_search_conversation_title_hours_many: "Hace {count} horas en <b>{conversationTitle}</b>",
    content_search_conversation_title_minutes: "Hace {count} minuto en <b>{conversationTitle}</b>",
    content_search_conversation_title_minutes_few: "Hace {count} minutos en <b>{conversationTitle}</b>",
    content_search_conversation_title_minutes_many: "Hace {count} minutos en <b>{conversationTitle}</b>",
    content_search_conversation_title_moment: "Hace un momento en <b>{conversationTitle}</b>",
    content_search_header: "Mensajes",
    content_search_aria: "Conversación con {topic}.",
    content_search_additional_results: "Mostrar más mensajes",

    contact_isSelected: "Seleccionado",

    label_text_headerMenuRemoveGroup: "Eliminar del grupo",
    label_text_headerMenuChat: "Chat",
    label_text_headerMenuInstantMessage: "Mensaje instantáneo",

    button_text_discover_agents: "Bots",
    label_text_discover_agents_page_header: "Bots",
    label_text_discover_agents_page_hint: "Sugerencia: interactúe con bots pulsando en ellos y agregándolos a sus contactos.",
    label_text_discover_agents_page_zero_results_text_part_1: "Parece que ya se ha conectado con todos los bots. Puede interactuar con ellos desde la página Contactos o buscándolos.",
    label_text_discover_agents_page_zero_results_text_part_2: "Estamos añadiendo nuevos bots continuamente, así que vuelva pronto.",

    label_text_contact_profile_details: "Detalles de contacto",
    label_text_contact_profile_skype_name: "Skype",
    label_text_contact_profile_skype_for_business_name: "Skype Empresarial",
    label_text_contact_profile_information: "Información",
    label_text_contact_profile_location: "Ubicación",
    label_text_contact_profile_birthday: "Fecha nacimiento",
    label_text_contact_profile_gender: "Sexo",
    label_text_contact_profile_language: "Idioma",
    label_text_contact_profile_agent_description: "Descripción",
    label_text_contact_profile_agent_author: "Autor",
    label_text_contact_profile_agent_certification: "Certificación",
    label_text_contact_profile_agent_rating: "Calificación promedio",
    label_text_view_profile_menu_item: "Ver perfil",

    label_text_agent_profile_label_agentid: "Bot",
    label_text_agent_profile_label_skype_certified: "Skype Certified",
    label_text_agent_profile_label_author: "Creado por",
    label_text_agent_profile_label_description: "Acerca de",
    label_text_agent_profile_label_website: "Sitio web",
    label_text_agent_profile_label_privacy: "Privacidad",
    label_text_agent_profile_value_privacy: "Este bot tendrá acceso a tu nombre para mostrar y nombre de usuario, así como a cualquier mensaje de chat o contenido que tú u otros participantes del grupo hayáis compartido con él.",
    label_text_agent_profile_link_text_terms_of_service: "Condiciones del servicio",
    label_text_agent_profile_link_text_privacy_statement: "Declaración de privacidad",
    label_text_agent_profile_label_rating: "Valoración",
    label_text_agent_profile_label_capabilities: "Esto es lo que puede hacer con este bot",
    label_text_agent_profile_label_extra_info: "Más información",
    label_text_agent_profile_capabilities_none: "leer las actualizaciones de este bot",
    label_text_agent_profile_capabilities_join_char: ", ",
    label_text_agent_profile_capabilities_audio_send: "hacer videollamadas",
    label_text_agent_profile_capabilities_video_send: "hacer videollamadas",
    label_text_agent_profile_capabilities_im_send: "enviar mensajes instantáneos",
    label_text_agent_profile_capabilities_screen_sharing: "compartir pantallas",
    label_text_agent_profile_capabilities_gvc: "hacer videollamadas grupales",
    label_text_agent_profile_capabilities_group_chat: "añadir bot a los chats grupales",
    label_text_agent_profile_capabilities_file_send: "enviar archivos",
    label_text_agent_profile_capabilities_contact_send: "enviar contactos",
    label_text_agent_profile_capabilities_videomessage_send: "enviar mensajes de vídeo",
    label_text_agent_profile_capabilities_audiomessage_send: "enviar mensajes de audio",
    label_text_agent_profile_capabilities_mediamessage_send: "enviar mensajes multimedia",
    label_text_agent_profile_capabilities_photo_send: "enviar fotos",
    label_text_agent_profile_capabilities_moji_send: "enviar Mojis",
    label_text_agent_profile_capabilities_location_send: "compartir ubicación",

    label_text_blockContact: "Bloquear contacto",
    label_text_block_agent: "Bloquear bot",
    label_text_blockContact_with_name: "Bloquear {name}",
    label_text_unblockContact: "Desbloquear contacto",
    label_text_unblock_agent: "Desbloquear bot",
    label_text_unblockContact_with_name: "Desbloquear {name}",
    label_text_deleteContact: "Eliminar contacto",
    label_text_delete_agent: "Eliminar bot",

    label_text_call_skype_audio: "Llamada de Skype",
    label_text_call_skype_video: "Videollamada",
    label_text_send_message: "Enviar un mensaje",
    label_text_call: "Llamada",
    label_text_call_phone_number: "Llamar a ({phoneNumber})",
    label_text_call_phone_number_home: "Llamar a casa ({phoneNumber})",
    label_text_call_phone_number_work: "Llamar a la oficina ({phoneNumber})",
    label_text_call_phone_number_cell: "Llamar al móvil ({phoneNumber})",
    label_text_call_phone_number_type: "Llamar a {phoneNumberType} ({phoneNumber})",
    label_text_phone_number_type_home: "Particular",
    label_text_phone_number_type_work: "Oficina",
    label_text_phone_number_type_cell: "Móvil",
    label_text_phone_number_type_other: "Otro",

    modal_blockContact_text_aria_label: "Bloquear contacto",
    modal_block_agent_text_aria_label: "Bloquear bot",
    modal_blockContact_text_title: "¿Estás seguro de que quieres bloquear a {displayName}?",
    modal_blockContact_text_message: "No podrán ponerse en contacto con su usuario y no aparecerán en la lista de contactos.",
    modal_block_contact_text_learn_more_link: "Más información",
    modal_blockContact_text_reportAbuse: "Denunciar a esta persona por abuso",
    modal_block_agent_text_reportAbuse: "Notificar abuso de este bot",
    select_placeholder_report_abuse_reason: "Seleccionar un motivo...",
    report_abuse_reason_option_spam: "Spam",
    report_abuse_reason_option_pornography: "Contiene desnudos o pornografía",
    report_abuse_reason_option_child_exploitation: "Explotación infantil",
    report_abuse_reason_option_harassment: "Acoso o amenazas",

    modal_deleteContact_text_aria_label: "Eliminar contacto",
    modal_delete_agent_text_aria_label: "Eliminar bot",
    modal_deleteContact_text_title: "¿Seguro que quieres eliminar {displayName}?",
    modal_deleteContact_text_message: "Se eliminará {displayName} de tu lista de contactos.",

    modal_device_disabled_chrome_title: "Para hacer llamadas de Skype, permita que Google Chrome acceda a la cámara y el micrófono.",
    modal_device_disabled_chrome_text: "Haga clic en el icono {image} de la barra de direcciones para permitir el acceso a la cámara y el micrófono.",
    modal_device_disabled_edge_title: "Para hacer llamadas de Skype, permita que Microsoft Edge acceda a la cámara y el micrófono.",
    modal_device_disabled_edge_text: "Solo tiene que volver a cargar esta página e intentar hacer otra llamada. A continuación, seleccione \"Sí\" cuando se le solicite que permita el acceso.",

    header_text_close: "Cerrar",
    header_text_participantsOthersCanJoin: "{count} participante. Otros usuarios pueden unirse",
    header_text_participantsOthersCanJoin_few: "{count} participantes, pueden unirse más usuarios",
    header_text_participantsOthersCanJoin_many: "{count} participantes, pueden unirse más usuarios",
    header_text_shareThisGroup: "Compartir este grupo",
    header_text_groupSettings: "Configuración del grupo",
    header_text_copyLink: "Copiar vínculo",
    header_text_copied: "Copiado",
    header_text_inviteViaEmail: "Invitar por correo",
    header_text_adminSettings: "Administrar grupo",
    header_text_makeHistoryAvailable: "Hacer que el historial de chat esté disponible para nuevos participantes",
    header_text_joinViaLink: "Crear un vínculo para que se una cualquier persona",
    header_text_allowOthersToJoin: "Permitir a otros usuarios unirse con un vínculo",
    header_text_othersCanJoin: "Otros usuarios se pueden unir con un vínculo",
    header_text_admin: "Administrador",
    header_text_admin_4b: "Moderador",
    header_text_guest: "Invitado",

    spaces_default_name: "Conversación sin título",
    spaces_tooltip_text: "Invita a otras personas enviándoles este vínculo, incluso si no están en Skype.",
    spaces_email_subject: "Estoy a punto para chatear mediante Skype",
    spaces_joining_disabled_message_start: "Activar <i>\"Crear un vínculo para que cualquier persona pueda unirse\"</i> desde el ",
    spaces_joining_disabled_anchor_text: "perfil ",
    spaces_joining_disabled_message_end: "para obtener un vínculo que se pueda compartir.",

    spaces_email_greeting: "Hola:",
    spaces_email_joinMe: "He creado un grupo en Skype para que chateemos, compartamos y colaboremos.",
    spaces_email_link: "Unirse haciendo clic en el vínculo",
    spaces_welcomeTitle: "La conversación ya está lista",
    spaces_welcomeMessage: "Comparta fotos, mensajes y mucho más con todos los usuarios que están por aquí o invite incluso a más personas compartiendo este vínculo con ellas",
    spaces_welcomeMessageWithoutLink: "Comparte fotos, mensajes y mucho más con todos los del grupo",
    spaces_welcomeRenameBtnTitle: "Cambiar nombre de conversación",
    spaces_welcomeRenameBtnMessage: "Haga que la conversación sea única",
    spaces_welcomeSettingsBtnTitle: "Configuración",
    spaces_welcomeSettingsBtnMessage: "Administre la conversación",
    spaces_anyoneElse: "¿Alguien más? Envíales un vínculo",
    spaces_conversation_renamed_success: "Se ha cambiado el nombre de la conversación a {conversationName}.",

    input_placeholder_addAnotherContact: "Agregar otro contacto",
    input_placeholder_typeContactName: "Escribir el nombre del contacto",

    message_text_hasLeftConversation: "{participant} ha salido de esta conversación",
    message_text_wasRemovedFromConversation: "{participant} ha eliminado a {removedParticipant} de esta conversación",
    message_text_youWereRemovedFromConversation: "Le eliminaron de esta conversación",
    message_text_joinedConversation: "{participant} se unió a esta conversación",
    message_text_joinConversationFailed: "{participant} no se pudo unir a la conversación",
    message_text_meJoinedConversation_one: "{participant} ya está chateando",
    message_text_meJoinedConversation_more: "{participants} y {participant} ya están chateando",
    message_text_wasAddedToConversation: "{participant} agregó a {contact} a esta conversación",
    message_text_botWasAddedToConversation: "Para chatear, comience su mensaje con <i>@{botName}</i>. El resto de mensajes del grupo están ocultos al bot.",
    message_text_joiningConversationWithBots: "<b>{botName} está participando en este grupo.</b></br>Para chatear, comience este mensaje con <i>@{botName}</i>. El resto de mensajes del grupo están ocultos al bot.",
    message_text_roleUpdated: "{who} actualizó el rol de {whom} a {role}",
    message_text_topicUpdated: "{participant} ha cambiado el tema de la conversación a \'{topic}\'",
    message_text_threadPictureUpdated: "{participant} ha cambiado la imagen de la conversación",
    message_text_historyClosed: "{participant} cerró el historial de la conversación",
    message_text_historyDisclosed: "{participant} divulgó el historial de la conversación",
    message_text_sentContacts: "Contactos enviados a la conversación",
    message_text_receivedContacts: "Contactos recibidos desde {from}",
    message_text_contactItem: "<li>{fullName} ({name})</li>",
    message_text_joiningEnabled: "{participant} habilitado para unirse a esta conversación",
    message_text_joiningDisabled: "{participant}  deshabilitado para unirse a esta conversación",
    message_text_legacyMemberAdded: "{participant} necesita actualizar Skype para participar en esta conversación. Para ayudarlo, envíalos a http://www.skype.com/en/download-skype/skype-for-computer/",
    message_text_legacyMemberUpgraded: "{participant} ahora puede participar en esta conversación.",
    message_text_emptyConversation: "No hay historial disponible para esta conversación",
    message_text_startedCall: "Llamada",
    message_text_startedGroupCall: "Llamada grupal",
    message_text_endedCall: "Llamada finalizada",
    message_text_endedGroupCall: "Llamada de grupo finalizada",
    message_text_outgoingCallNoAnswer: "Llamada, no contesta",
    message_text_outgoingGroupCallNoAnswer: "Llamada de grupo, sin respuesta",
    message_text_missedCall: "Llamada perdida",
    message_text_missedGroupCall: "Llamada de grupo perdida",
    message_text_unknownMessageType: "Tipo de mensaje desconocido \"{mesageType}\"",
    message_text_fileTransferNotSupported: "Skype para Web no es compatible con la recepción de archivos mediante una red P2P",
    message_text_parsing_error: "Error durante el análisis del mensaje.",
    message_text_unsupportedVideoMessageYet: "La recepción de mensajes de video no es compatible con Skype para Web",
    message_text_unsupportedAudioMessageYet: "No se admite la recepción de mensajes de audio en Skype para Web",
    message_text_guestRemovedBySystem: "La cuenta de invitado de {participant} expiró",
    message_text_pollsFeatureDisabled: "Los sondeos no están disponibles en este momento. Vuelve a intentarlo más tarde.",
    message_text_ngcUpgradeMessage_one: "<strong>{participant}</strong> no pudo unirse a esta llamada. Puede que deba conectarse, actualizar Skype o que esté usando un dispositivo no compatible. Obtenga más información en {link}",
    message_text_ngcUpgradeMessage_many: "<strong>{participantList}</strong> y <strong>{lastParticipant}</strong> no pudieron unirse a esta llamada. Puede que deban conectarse, actualizar Skype o que estén usando un dispositivo no compatible. Obtenga más información en {link}",

    message_text_swift_card: "Tarjeta",
    message_text_swift_cards: "Tarjetas",
    message_text_swift_receipt: "Recibo",
    message_text_swift_signIn: "Iniciar sesión",
    message_text_swift_defaultTitle: "Le envió un mensaje",
    message_text_swift_defaultGroupTitle: "{displayName} envió un mensaje",
    message_text_swift_vat: "IVA",
    message_text_swift_tax: "Impuestos",
    message_text_swift_totalPrice: "Total",
    message_text_swift_unsupported: "No podemos mostrar esta tarjeta en su versión de Skype.",
    message_text_swift_unsupported_button: "Siguiente",
    message_text_swift_showImageTitle: "Ampliar imagen",
    message_text_swift_signInTitle: "Conectar",
    message_text_swift_prevCard: "Mostrar anterior",
    message_text_swift_nextCard: "Mostrar siguiente",
    message_text_swift_showAll: "Mostrar todo",
    message_text_swift_showLess: "Mostrar menos",

    accessibility_swift_openUrl: "Haga clic para abrir el sitio web en su navegador",
    accessibility_swift_imBack: "Haga clic para enviar la respuesta al bot",
    accessibility_swift_call: "Haga clic para llamar",
    accessibility_swift_showImage: "Haga clic para ampliar la imagen",
    accessibility_swift_action_prefix: "Haga clic para {swiftAction}",

    message_text_pluginFree_windowsUpdate_line1: "Actualice a la versión más reciente de Windows 10 para disfrutar de llamadas instantáneas en Microsoft Edge {update_link}.",
    message_text_pluginFree_windowsUpdate_line2: "Como alternativa, puede instalar el complemento Skype para Web si aún no lo ha hecho.",
    message_text_pluginFree_screenSharingFallback_line1: "Pronto estará disponible el uso compartido de la pantalla.",
    message_text_pluginFree_screenSharingFallback_line2: "Como alternativa, cambie a la aplicación Skype para el dispositivo para poder disponer del uso compartido de la pantalla {upgrade_link}.",
    message_text_pluginFree_microphoneAccess_edge: "No se ha detectarlo ningún micrófono. Conecte uno o compruebe la configuración de privacidad del micrófono en Configuración -> Privacidad -> Micrófono.",
    message_text_pluginFree_microphoneAccess_others: "No se ha detectarlo ningún micrófono. Conecte uno o compruebe la configuración de privacidad del micrófono para el dispositivo y el explorador.",
    message_text_pluginFree_outgoingP2P_line1: "El contacto al que está intentando llamar está utilizando una versión desactualizada de Skype. Envíele este vínculo para actualizar Skype {upgrade_link}.",
    message_text_pluginFree_outgoingP2P_line2: "Como alternativa, aún puede ponerse en contacto con esta persona instalando primero el complemento Skype para Web.",
    message_text_pluginFree_outgoingP2P_line3: "También puede seguir en contacto con ellos cambiando a la aplicación de Skype para su dispositivo {upgrade_link}.",
    message_text_pluginFree_incomingP2P_line1: "Un contacto está intentando ponerse en contacto con usted utilizando una versión desactualizada de Skype. Envíele este vínculo para actualizar Skype {upgrade_link}.",
    message_text_pluginFree_incomingP2P_line2: "Como alternativa, puede recibir la llamada instalando primero el complemento Skype para Web.",
    message_text_pluginFree_incomingP2P_line3: "También puede recibir sus llamadas cambiando a la aplicación de Skype para su dispositivo {upgrade_link}.",
    message_text_pluginFree_incomingP2P_line4: "Esta persona intentó contactar con usted pero se produjo un problema al conectar la llamada. Intente devolverle la llamada.",
    message_text_pluginFree_noVideoCapability: "En esta plataforma todavía no está disponible el soporte vídeo.",

    message_text_suggestedContactGreeting: "<strong>{displayName}</strong> es un contacto de la libreta de direcciones pero, para poder chatear con él, primero debes conectarte",
    message_text_suggestedContactConnectAction: "Conectar en Skype",
    message_text_contactBlockedMessage: "Has bloqueado a <strong>{displayName}</strong>",
    message_text_contactAccepted: "Contacto aceptado",
    message_text_addingContactRequest: "<strong>{id}</strong> desea agregarlo como contacto",
    message_text_isNowAContact: "<strong>{id}</strong> es ahora un contacto",
    message_text_contactRequestGreeting: "Hola, {displayName}, me gustaría agregarlo como contacto.",
    message_text_contactRequestIsNowContact: "<strong>{displayName}</strong> es ahora un contacto",
    message_text_contactRequestOutgoingMessage: "<strong>{displayName}</strong> no está en su lista de contactos",
    message_text_contactRequestOutgoingResendMessage: "Solicitud de contacto enviada",
    message_text_contactRequestOutgoingResendAction: "Volver a enviar la solicitud de contacto",
    message_text_contactRequestIncomingMessage: "<strong>{displayName}</strong> desea agregarlo como contacto",
    message_text_contactRequestSendAction: "añadir a contactos",
    message_text_contactRequestAcceptAction: "aceptar",
    message_text_contactRequestDeclineAction: "rechazar",
    message_text_unblockContact: "desbloquear",
    message_text_timeStampMessage: "Enviado en: ",
    message_text_longTimeStamp: "{date} a las {time}",
    message_text_removed: "Eliminado el {date} a las {time}",

    message_text_presenceAvailable: "Disponible",
    message_text_presenceOnline: "Conectado",
    message_text_presenceNotAvailable: "No disponible",
    message_text_presenceOffline: "Desconectado",
    message_text_presenceHidden: "Invisible",
    message_text_contactTitleLocal: "Contactos",
    message_text_contactTitleDirectory: "Directorio",
    message_text_contactBlocked: "Bloqueado",

    button_translations_see_original_message: "Ver el original",
    button_translations_see_translated_message: "Ver la traducción",
    button_translator_translatorSettings: "Skype Translator",
    label_translator_translatorSettings: "Vista previa",
    button_translator_translatorSettingsOn: "Activado",
    button_translator_translatorSettingsOff: "Desactivado",
    label_translator_translatorOn: "Activado",
    label_translator_translatorOff: "Desactivado",

    label_translator_selected_theirLanguage: "Se seleccionó {language} para {name}",
    label_translator_selected_myLanguage: "{language} seleccionado para usted mismo",

    button_text_searchDirectory: "Buscar en el directorio de Skype",
    message_text_emptySearchResults: "No se encontraron resultados",

    message_text_groupSearchResultsTitle: "Grupos",
    message_title_allContacts: "Todos los contactos",
    message_bucketName_other: "#",
    message_not_delivered_text: "Este mensaje no se entregó",
    message_edited_text: "Este mensaje se editó.",
    message_more_search_results_available: "Demasiados resultados. Pruebe a restringir la búsqueda.",

    label_text_newConv: "Nueva",

    newbee_text_header: "Empieza la conversación",
    newbee_text_cta: "Encuentra a tus amigos escribiendo su nombre o su correo electrónico en el campo Buscar en Skype.",
    newbee_text_cta_4b: "Busque a sus compañeros escribiendo su nombre en el campo de búsqueda.",

    contactPage_text_menuLink: "Contactos",
    contactPage_text_header: "Contactos",
    contactPage_text_tab_allContacts: "Todos los contactos",
    contactPage_text_tab_available: "Conectado",
    contactPage_text_tab_work: "Trabajo",
    contactPage_text_tab_agents: "Bots",
    contactPage_text_hint_search: "Sugerencia: agrega contactos nuevos desde la barra de búsqueda",
    contactPage_text_manage_contacts_button: "Administrar contactos",
    contactPage_text_informational_message: "Obtenga la aplicación de Skype Empresarial para hacer videollamadas y reuniones en línea.",

    settings_page_text_header: "Configuración",
    settings_pane_opened: "Panel Configuración abierto",

    settings_messaging_category_title: "Mensajes",     //as in "group of Messaging settings"
    settings_privacy_category_title: "Privacidad",
    settings_unlisted_category_title: "Otros",
    settings_contacts_category_title: "Contactos",
    settings_about_category_title: "Acerca de",
    settings_notifications_category_title: "Notificaciones",
    settings_unknownOption_title: "Opción desconocida: {id}",
    settings_unknownOption_alt_text: "Opción desconocida: {id}",

    //ATTN de-de and similar: please insert soft hypens (U+00AD) if a single "word" is more than 20 letters long.
    settings_mentionsEnabled_title: "Notificaciones @menciones",      //As in mention someone by typing his user name with the @ character prefix.

    // "username" in "(@&lt;username&gt;)" is a placeholder. For example, to mention an user named john2016 you type "@john2016"
    // ATTN RTL languages: The (@&lt;username&gt;) must be LTR embedded (U+202a and U+202c) so the non-alphabetic symbols are rendered in the correct order
    settings_mentionsEnabled_alt_text: "Notificarme siempre que alguien me mencione en Skype. (@&lt;username&gt;)",
    settings_youtube_player_title: "Reproductor de YouTube",
    settings_youtube_player_alt_text: "Usar directamente el reproductor de Youtube para obtener una vista previa de los videos que envío o recibo.",
    settings_urlPreview_title: "Vista previas de vínculos web",
    settings_urlPreview_alt_text: "Mostrarme una vista previa de sitios web que envío o recibo a través de Skype.",
    settings_filePaste_title: "Habilitar el pegado de imágenes",
    settings_filePaste_alt_text: "Habilitar la posibilidad de pegar imágenes desde el Portapapeles directamente en el chat",

    settings_skypeCallPolicy_title: "Permitir llamadas de:",
    settings_skypeVideoPolicy_title: "Permitir video y pantalla compartida de:",

    settings_camera_title: "Cámara",
    settings_microphone_title: "Micrófono",
    settings_speaker_title: "Altavoz",
    settings_no_camera_title: "No hay ninguna cámara disponible",
    settings_no_microphone_title: "No hay ningún micrófono disponible",
    settings_no_speaker_title: "No hay ningún altavoz disponible",
    settings_close_title: "Cerrar",

    settings_default_device_name: "Seleccionado automáticamente",

    settings_typingIndicator_title: "Indicador de escritura",
    settings_typingIndicator_alt_text: "Mostrar que estoy escribiendo",

    settings_translator_title: "Traductor",
    settings_translator_title_alt_text: "Habilitar Skype Translator",

    settings_sendReadReceipts_title: "Enviar confirmaciones de lectura",
    settings_sendReadReceipts_alt_text: "Mostrar si los otros usuarios leyeron los mensajes. Si se desactiva está opción, tampoco verá sus confirmaciones de lectura.",

    settings_privacy_opt_1_title: "Cualquiera",             //as in "<Allow calls from> anyone"
    settings_privacy_opt_2_title: "Solo contactos",      //as in "<Allow calls from> my contacts only"
    settings_privacy_opt_3_title: "Nadie",             //as in "<Allow calls from> nobody"

    settings_short_circuit_my_contact_list: "Mi lista de contactos",
    settings_short_circuit_title: "Agregar amigos automáticamente",
    settings_short_circuit_description: "Skype comprobará tus libretas de direcciones y agregará automáticamente contactos que conoces a tu lista de contactos de Skype.",
    settings_short_circuit_deny: "No agregar amigos automáticamente",
    settings_short_circuit_deny_title: "Deberá buscar y agregar contactos nuevos manualmente.",
    settings_short_circuit_manage_contacts: "Administrar libretas de direcciones",
    settings_short_circuit_auto_buddy_discovery_title: "Cómo me encuentran los usuarios:",
    settings_short_circuit_auto_buddy_discovery_description: "Estos detalles de contacto se pueden usar para buscarle en Skype.",
    settings_short_circuit_remove: "Quitar",
    settings_short_circuit_add_number: "Añadir número nuevo",

    settings_notifications_title: "Notificaciones",
    settings_notifications_alt_text: "Recibir notificaciones para los mensajes de chat nuevos",
    settings_notifications_sound_title: "Sonido",
    settings_notifications_sound_alt_text: "Activar o desactivar sonidos de notificación",

    short_circuit_contacts_page_message: "Añada personas de su libreta de direcciones rápidamente",
    short_circuit_contacts_page_message_v2: "Agregar automáticamente amigos de la libreta de direcciones",
    short_circuit_contacts_page_cta: "Añadir amigos",

    about_app_version: "Versión de la aplicación",
    about_assets_version: "Versión de los activos",
    about_plugin_version: "Versión del complemento",
    about_plugin_not_available: "No disponible",
    about_faq: "Preguntas más frecuentes",

    message_text_callingNotSupportedBrowser: "Tu navegador no admite las llamadas de audio ni las videollamadas",
    message_text_callingNotSupportedOS: "Tu SO no admite las llamadas de audio ni las videollamadas",
    message_text_callingIsDisabled: "Llamar está desactivado actualmente.",

    chatLogmenuItem_text_quote: "Citar mensaje",
    chatLogmenuItem_text_edit: "Editar mensaje",
    chatLogmenuItem_text_remove: "Quitar mensaje",
    chatLogmenuItem_text_like: "Mensaje de Me gusta",
    chatLogmenuItem_text_save: "Guardar",
    chatLogmenuItem_copy_link: "Copiar vínculo",
    chatLogmenuItem_open_link: "Abrir",
    chatLogIntroText_text: "Chatee con personas que editan este archivo en Office Online. | Este chat no se guardará cuando cierre el archivo.",

    recentItemMenuItem_text_leave: "Abandonar la conversación",
    recentItemMenuItem_text_remove: "Eliminar conversación",
    recentItemMenuItem_text_remove_4b: "Cerrar conversación",
    recentItemMenuItem_text_markRead: "Mark as read",

    actionsMenuItem_text_addParticipants: "Agregar participantes",
    actionsMenuItem_text_scheduleCall: "Programar una llamada",

    typingIndicator_label_oneParticipant: "{firstParticipantName} está escribiendo...",
    typingIndicator_label_twoParticipants: "{firstParticipantName} y {secondParticipantName} están escribiendo...",
    typingIndicator_label_multipleParticipants: "{firstParticipantName}, {secondParticipantName} y otros {count} están escribiendo...",
    typingIndicator_label_multipleParticipants_few: "{firstParticipantName}, {secondParticipantName} y otros {count} están escribiendo...",
    typingIndicator_label_multipleParticipants_many: "{firstParticipantName}, {secondParticipantName} y otros {count} están escribiendo...",

    button_text_emoticons: "Emoticonos",
    button_title_emoticons: "Emoticonos",
    button_text_videoCall: "Videollamada",
    button_text_audioCall: "Llamada de audio",
    button_text_joinCall: "Unirse a la llamada",
    button_text_joinCallWithVideo: "Unirse a la llamada con vídeo",
    button_text_addParticipants: "Añadir",
    button_text_cancelAddParticipants: "Cancelar",
    button_text_createConversation: "Crear",
    button_text_filePicker: "Compartir una foto",
    button_text_chatInputActionPicker: "Enviar archivos y elementos multimedia",
    button_text_poll: "Enviar un sondeo",
    button_text_moreActions: "Más acciones",
    button_text_closeSettings: "Cerrar",

    callScreen_text_terminationPrompt: "Ahora mismo estás en medio de una llamada. ¿Estás seguro de que quieres colgar y cerrar Skype?",
    callscreen_text_terminationMessage: "Llamada finalizada",
    callscreen_text_autoCallConnectingMessage: "Esperando a que se unan otros usuarios...",
    callscreen_text_autoCallTimeoutMessage: "Parece que es el único aquí. Intente unirse a la llamada más tarde",
    callscreen_text_autoCallFailedMessage: "No se pudo configurar la llamada. Inténtelo de nuevo más tarde",
    callscreen_text_statusMessageConnecting: "Conectando...",
    callscreen_text_statusMessageScreenReaderConnecting: "Conectando con {contactName}",
    callscreen_text_statusMessageScreenReaderEnding_less_than_minute: "Llamada finalizada; duración: menos de un minuto",
    callscreen_text_statusMessageScreenReaderEnding_minutes: "Llamada finalizada; duración: {count} minuto",
    callscreen_text_statusMessageScreenReaderEnding_minutes_few: "Llamada finalizada; duración: {count} minutos",
    callscreen_text_statusMessageScreenReaderEnding_minutes_many: "Llamada finalizada; duración: {count} minutos",
    callscreen_text_participant_joined_notification: "{name} se unió",
    callscreen_text_participant_left_notification: "{name} salió",
    callscreen_text_participant_screen_shared_notification: "{name} ha comenzado a compartir la pantalla",
    callscreen_text_participant_screen_unshared_notification: "{name} ha dejado de compartir la pantalla",
    callscreen_text_statusMessageCalling: "Llamando...",
    callscreen_text_enterFullscreen: "Activar pantalla completa",
    callscreen_text_exitFullscreen: "Salir del modo pantalla completa",
    callscreen_text_videoOn: "Activar vídeo",
    callscreen_text_videoOff: "Desactivar vídeo",
    callscreen_text_plusButton: "Agregar participantes, compartir pantallas y más",
    callscreen_text_shareScreens: "Compartir pantallas...",
    callscreen_text_shareScreen: "Compartir pantalla",
    callscreen_text_stopSharingScreen: "Dejar de compartir",
    callscreen_text_addParticipants: "Agregar contactos a esta llamada",
    callscreen_text_microphoneOn: "Activar micrófono",
    callscreen_text_microphoneOff: "Desactivar micrófono",
    callscreen_text_endCall: "Finalizar llamada",
    callscreen_text_participants: "{count} en la llamada",
    callscreen_text_showChat: "Mostrar MI",
    callscreen_text_showContacts: "Mostrar contactos",
    callscreen_text_hangUp: "Colgar",
    callscreen_text_addParticipantsToCall: "Agregar contactos a esta llamada",
    callScreen_text_andMore: "y más",
    callscreen_text_dialpadOn: "Activar el teclado de marcado",
    callscreen_text_dialpadOff: "Desactivar el teclado de marcado",
    callscreen_title_zoom: "Haz doble clic para ampliar",
    callscreen_text_showAVSettings: "Configuración de vídeo y audio",
    callscreen_text_showSidebar: "Mostrar barra lateral",
    callscreen_text_hideSidebar: "Ocultar barra lateral",

    toast_incoming_text_title: "Llamada entrante",
    toast_incoming_text_acceptWithVideo: "Aceptar con vídeo",
    toast_incoming_text_acceptWithAudio: "Aceptar con audio",
    toast_incoming_text_reject: "Rechazar llamada",
    toast_install_text_title: "está intentando llamarte",
    toast_install_text_installButton: "Instalar complemento",
    toast_install_text_message: "Necesitarás un complemento para realizar llamadas de Skype",

    pluginInstall_main_close_screen_title: "¿Estás seguro de que deseas irte?",
    pluginInstall_main_close_screen_subtitle: "Ya casi has acabado con la configuración de llamadas de Skype.",
    pluginInstall_main_close_screen_finish_text: "Finalizar instalación",
    pluginInstall_main_close_screen_leave_text: "Abandonar",

    pluginInstall_extension_main_text_title: "Habilita las llamadas de Skype en unos pocos y sencillos pasos...",
    pluginInstall_extension_main_text_subtitle: "Empieza añadiendo la extensión de llamadas de Skype a Chrome",
    pluginInstall_extension_main_text_add_extension: "Agregar extensión",

    pluginInstall_extension_main_installed_text_title: "¡Genial!",
    pluginInstall_extension_main_installed_text_subtitle: "Ahora instala el complemento de Skype para la web y ya estarás preparado",
    pluginInstall_extension_main_installed_get_plugin_text: "Obtener el complemento",

    pluginInstall_extension_main_install_failed_text_title: "Error",
    pluginInstall_extension_main_install_failed_text_subtitle: "Inténtalo de nuevo...",
    pluginInstall_extension_main_install_failed_go_to_chrome_webstore_text: "Ir a Chrome web store",

    pluginInstall_main_text_close: "Cerrar",
    pluginInstall_main_text_title: "¿Quieres llamar?",
    pluginInstall_main_text_subtitle: "Tienes que instalar el complemento para realizar llamadas de Skype",
    pluginInstall_main_text_install: "Instalar complemento",
    pluginInstall_steps_text_restart: "Reiniciar",
    pluginInstall_steps_text_title: "Instalemos el complemento.",
    pluginInstall_steps_text_subtitle: "Sigue estos tres pasos para configurar las llamadas de Skype",
    pluginInstall_steps_text_termsAndPrivacy: "Al instalar el complemento de Skype, confirma que ha leído y aceptado los {terms_link} y la {privacy_link} de Skype.",
    pluginInstall_steps_text_termsLink: "Condiciones de uso",
    pluginInstall_steps_text_privacyLink: "Política de privacidad de Skype",
    pluginInstall_mac_chrome_text_download: "Haz clic en el archivo de complemento.",
    pluginInstall_mac_chrome_text_install: "Sigue las instrucciones.",
    pluginInstall_mac_chrome_text_enjoy: "Disfruta de llamadas de Skype gratuitas.",
    pluginInstall_mac_chrome_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_mac_safari_text_download: "Ve a descargas y haz doble clic sobre el archivo de complemento.",
    pluginInstall_mac_safari_text_install: "Sigue las instrucciones para instalar el complemento.",
    pluginInstall_mac_safari_text_enjoy: "Disfruta de llamadas de Skype gratuitas desde la web.",
    pluginInstall_mac_safari_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_mac_firefox_text_download: "Abrir el archivo de complemento.",
    pluginInstall_mac_firefox_text_install: "Sigue las instrucciones.",
    pluginInstall_mac_firefox_text_enjoy: "Disfruta de llamadas de Skype gratuitas.",
    pluginInstall_mac_firefox_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_mac_unknown_download: "Ve a descargas y haz doble clic sobre el archivo de complemento.",
    pluginInstall_mac_unknown_install: "Sigue las instrucciones para instalar el complemento.",
    pluginInstall_mac_unknown_enjoy: "Disfruta de llamadas de Skype gratuitas desde la web.",
    pluginInstall_windows_chrome_text_download: "Haz clic en el archivo de complemento.",
    pluginInstall_windows_chrome_text_install: "Espera a que se instale el complemento.",
    pluginInstall_windows_chrome_text_enjoy: "Disfruta de llamadas de Skype gratuitas.",
    pluginInstall_windows_chrome_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_windows_msie_text_download: "Haz clic en \"Ejecutar\" para comenzar.",
    pluginInstall_windows_msie_text_install: "Espera a que se instale el complemento.",
    pluginInstall_windows_msie_text_enjoy: "Disfruta de llamadas de Skype gratuitas.",
    pluginInstall_windows_msie_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_windows_firefox_text_download: "Haz clic en \"Guardar archivo\" para comenzar.",
    pluginInstall_windows_firefox_text_install: "Haz clic en el archivo de complemento.",
    pluginInstall_windows_firefox_text_enjoy: "Disfruta de llamadas de Skype gratuitas.",
    pluginInstall_windows_firefox_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_windows_unknown_text_download: "Haz clic en \"Ejecutar\" para comenzar.",
    pluginInstall_windows_unknown_text_install: "Espera a que se instale el complemento.",
    pluginInstall_windows_unknown_text_enjoy: "Disfruta de llamadas de Skype gratuitas.",
    pluginInstall_windows_unknown_text_enjoy_4b: "Realice llamadas de Skype.",
    pluginInstall_unblock_text_title: "Habilitar el complemento de Skype",
    pluginInstall_unblock_text_chrome_subtitle: "Haga clic en el icono del complemento en la barra de direcciones y seleccione \"Permitir siempre complementos en web.skype.com\" para continuar con esta llamada.",
    pluginInstall_unblock_text_firefox_subtitle: "Haga clic en el icono del complemento en la barra de direcciones y seleccione \"Permitir y recordar\" para continuar con esta llamada.",
    pluginInstall_callback_text_title: "Llamar a {displayName}",
    pluginInstall_callback_text_subtitle: "Ya tienes el complemento instalado, así que ya puedes comenzar a llamar",
    pluginInstall_callback_text_call: "Llamar",
    pluginInstall_callback_text_accept: "Aceptar llamada",
    pluginInstall_callback_text_notNow: "Ahora no",
    pluginInstall_label_text_start: "Instalación de complemento: inicio",
    pluginInstall_label_text_download: "Instalación de complemento: descarga",
    pluginInstall_label_text_unblock: "Instalación del complemento: desbloquear el complemento de Skype",
    pluginInstall_label_text_continue: "Instalación de complemento: continuar la llamada",
    pluginInstall_label_text_autoUpdateDisclaimer: "Este complemento se actualizará automáticamente para ofrecerte una experiencia óptima. Si no quieres recibir las actualizaciones, no instales el complemento.",

    notification_text_osNotSupported: "Llamada perdida de {callerName}. Las llamadas de audio y de vídeo no son compatibles con este sistema operativo.",
    notification_text_browserNotSupported: "Llamada perdida de {callerName}. Las llamadas de audio y de vídeo no son compatibles con este sistema operativo.",
    notification_text_learnMore: "Obtener más información",
    notification_text_hardware_camera: "No se encontró ninguna cámara",
    notification_text_hardware_mic: "No se encontró el micrófono",
    notification_text_hardware_speaker: "No se encontró ningún altavoz",

    notification_text_group_conversation_from: "Chat grupal de",

    notification_text_avatar_not_supported_image_type: "No se admite el tipo de imagen que intentó cargar",
    notification_text_avatar_upload_error: "No se puede cambiar la imagen de perfil, inténtelo de nuevo.",

    enable_browser_notifications_toast: "Active ahora las notificaciones de chat mejoradas para no volverse a perder ni un mensaje.",
    enable_browser_notifications_text: "Reciba notificaciones con los mensajes nuevos.",
    enable_browser_notification_link_text: "Activar las notificaciones mejoradas",

    allow_browser_notifications_header: "No se pierda ni un mensaje",
    allow_browser_notifications_text: "Haga clic en \"Permitir\" para recibir notificaciones de chat en su explorador.",

    media_clicktoplay: "Haga clic aquí para reproducir",

    media_picturesharing_one: "compartió una foto",
    media_picturesharing_group: "{senderName} compartió una foto",
    media_picturesharing_label: "Abrir foto en una ventana nueva",

    media_voice_message: "Mensaje de voz",
    media_audiosharing_one: "compartió un mensaje de audio",
    media_audiosharing_group: "{senderName} compartió un mensaje de audio",

    media_videosharing_one: "compartió un vídeo",
    media_videosharing_group: "{senderName} compartió un vídeo",

    media_videomessage_expired: "El mensaje de vídeo expiró",
    media_audiomessage_expired: "El mensaje de audio ha vencido",

    mediaPlayer_play: "Reproducir",
    mediaPlayer_pause: "Pausar",
    videoPlayer_fullscreen: "Pantalla completa",
    videoPlayer_exitFullscreen: "Salir de pantalla completa",

    action_button_confirm: "Confirmar",
    action_button_cancel: "Cancelar",
    action_button_save: "Guardar",
    action_button_block: "Bloquear",
    action_button_delete: "Eliminar",
    action_button_delete_4b: "Cerrar",
    action_button_send: "Enviar",
    action_button_share_conversation: "Compartir conversación",
    action_button_leave: "Salir",

    media_mojisharing_one: "compartió un Moji",
    media_mojisharing_group: "{senderName} compartió un Moji",
    emoticonPicker_heading_label: "Seleccionar un emoticono",

    accessibility_recentItem_oneToOne: "Conversación con {topic}. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_oneToOne_many: "Conversación con {topic}. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_oneToOne_unread: "Conversación con {topic}, {count} mensaje sin leer. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_oneToOne_unread_many: "Conversación con {topic}, {count} mensajes sin leer. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_group_unread: "Conversación de grupo con {count} mensaje sin leer {topic}. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_group_unread_many: "Conversación de grupo con {count} mensajes sin leer {topic}. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_group: "Conversación de grupo {topic}. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_group_many: "Conversación de grupo {topic}. Presiona Mayús + F10 para ver más opciones.",
    accessibility_recentItem_recent_group: "Conversaciones recientes",
    accessibility_chatLog_newMessage: "Nuevo mensaje de {author}, {content}",
    accessibility_chatLog_newMessage_withoutAuthor: "Nuevo mensaje: {content}",

    accessibility_searching: "Buscando",
    accessibility_searchItem_oneToOne: "{contactName}, {id}, {status}, {index} de {totalResults} en Contactos.",
    accessibility_searchItem_group: "Grupo {groupName}, {index} de {totalResults} en Grupos.",
    accessibility_searchItem_group_displayMessage: "Grupo {groupName}, {displayMessage}, {index} de {totalResults} en Grupos.",
    accessibility_searchItem_directoryList: "{contactName}, {id}, {status}, {index} de {totalResults} en el directorio de Skype.",

    accessibility_localSearchUpdated: "Se ha actualizado la búsqueda y se ha encontrado {totalSearchResults} resultado en tus contactos y grupos. {peopleSearchResults} en Contactos y {groupsSearchResults} en Grupos.",
    accessibility_localSearchUpdated_few: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados en tus contactos y grupos. {peopleSearchResults} en Contactos y {groupsSearchResults} en Grupos.",
    accessibility_localSearchUpdated_many: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados en tus contactos y grupos. {peopleSearchResults} en Contactos y {groupsSearchResults} en Grupos.",
    accessibility_localSearchUpdated_4b: "Se ha actualizado la búsqueda y se ha encontrado {totalSearchResults} resultado en los contactos.",
    accessibility_localSearchUpdated_4b_few: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados en los contactos.",
    accessibility_localSearchUpdated_4b_many: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados en los contactos.",
    accessibility_localSearchNoResults: "La búsqueda se ha actualizado y no se encontraron resultados en sus contactos y grupos.",
    accessibility_localSearchNoResults_4b: "Se ha actualizado la búsqueda y no se ha encontrado ningún resultado en los contactos.",
    accessibility_searchSkypeDirectory: "Pulse Entrar para buscar en el Directorio de Skype.",
    accessibility_clearSearchField_ariaLabel: "Borrar campo de datos de la búsqueda.",

    accessibility_skypeDirectorySearchUpdated: "Se ha actualizado la búsqueda y se ha encontrado {totalSearchResults} resultado en el directorio de Skype.",
    accessibility_skypeDirectorySearchUpdated_few: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados en el directorio de Skype.",
    accessibility_skypeDirectorySearchUpdated_many: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados en el directorio de Skype.",

    accessibility_totalSearchUpdated: "Se ha actualizado la búsqueda y se ha encontrado {totalSearchResults} resultado. {peopleSearchResults} en Contactos, {groupsSearchResults} en Grupos y {SkypeDirectorySearchResults} en el directorio de Skype.",
    accessibility_totalSearchUpdated_few: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados. {peopleSearchResults} en Contactos, {groupsSearchResults} en Grupos y {SkypeDirectorySearchResults} en el directorio de Skype.",
    accessibility_totalSearchUpdated_many: "Se ha actualizado la búsqueda y se han encontrado {totalSearchResults} resultados. {peopleSearchResults} en Contactos, {groupsSearchResults} en Grupos y {SkypeDirectorySearchResults} en el directorio de Skype.",
    accessibility_totalSearchNoResults: "Se ha actualizado la búsqueda y no se han encontrado resultados en tus contactos y grupos, ni en el directorio de Skype.",

    accessibility_contactProfile_headingWithClosedProfile: "Abra el perfil: {topic}.",
    accessibility_contactProfile_openedProfile: "Abrió el perfil de {topic}.",
    accessibility_contactProfile_closedProfile: "Cerró el perfil de {topic}.",
    accessibility_contactProfile_headingWithOpenedProfile: "Cierre el perfil: {topic}.",

    accessibility_groupProfile_headingWithClosedProfile: "Abra el perfil de grupo.",
    accessibility_groupProfile_headingWithOpenedProfile: "Cierre el perfil de grupo.",
    accessibility_groupProfile_attendeeMenu: "{participantName}. Más opciones.",
    accessibility_groupProfile_adminMenu: "{participantName}, administrador. Más opciones.",
    accessibility_groupProfile_guestMenu: "{participantName}, invitado. Más opciones.",
    accessibility_groupProfile_historyToggle_on: "Poner el historial del chat a disposición de los usuarios que se unen. Activado.",
    accessibility_groupProfile_historyToggle_off: "Poner el historial del chat a disposición de los que se unen. Desactivado.",
    accessibility_groupProfile_joiningToggle_on: "Permitir unirse a este grupo mediante un vínculo. Activado.",
    accessibility_groupProfile_joiningToggle_off: "Permitir unirse a este grupo mediante un vínculo. Desactivado.",

    accessibility_me_expandProfile: "Expandir perfil",
    accessibility_me_collapseProfile: "Reducir el perfil",
    accessibility_me_availabilityOnAriaLabel: "El estado de conexión se definió como conectado (notificaciones activadas).",
    accessibility_me_availabilityOffAriaLabel: "El estado de conexión se definió como invisible (notificaciones desactivadas).",

    accessibility_contactPickerUpdated: "Se actualizó la búsqueda y se encontró {totalSearchResults} resultado en los contactos.",
    accessibility_contactPickerUpdated_few: "Se actualizó la búsqueda y se encontraron {totalSearchResults} resultados en los contactos.",
    accessibility_contactPickerUpdated_many: "Se actualizó la búsqueda y se encontraron {totalSearchResults} resultados en los contactos.",
    accessibility_contactPickerNoResults: "Se actualizó la búsqueda y no se encontraron resultados en los contactos.",
    accessibility_contactPickerResultRemoved: "{displayName} eliminado de la nueva lista de participantes en la conversación",

    accessibility_contact_blocked_success: "Contacto bloqueado",
    accessibility_contact_blocked_failure: "Error al bloquear el contacto",
    accessibility_contact_unblocked_success: "Contacto desbloqueado",
    accessibility_contact_unblocked_failure: "Error al desbloquear el contacto",
    accessibility_contact_request_sent_success: "Solicitud de contacto enviada",
    accessibility_contact_request_sent_failure: "Error al enviar la solicitud de contacto",
    accessibility_contact_request_accepted_success: "Solicitud de contacto aceptada",
    accessibility_contact_request_accepted_failure: "Error al aceptar la solicitud de contacto",
    accessibility_contact_request_declined_success: "Solicitud de contacto rechazada",
    accessibility_contact_request_declined_failure: "Error al rechazar la solicitud de contacto",
    accessibility_contact_sent: "Contacto envia.",
    accessibility_contact_deleted_success: "Contacto eliminado",
    accessibility_contact_deleted_failure: "No se pudo eliminar el contacto",
    accessibility_contact_add_favorite_success: "Contacto agregado a favoritos",
    accessibility_contact_add_favorite_failure: "No se pudo agregar el contacto a favoritos",
    accessibility_contact_remove_favorite_success: "Contacto eliminado de los favoritos",
    accessibility_contact_remove_favorite_failure: "No se pudo eliminar el contacto de favoritos",

    accessibility_selectBox_expanded: "Combo box expanded",

    accessibility_addPeopleToConversation_ariaLabel: "Añadir personas a esta conversación",
    addPeopleToConversation_tooltip: "Añadir personas",
    accessibility_startVideoCall_ariaLabel: "Videollamada",
    startVideoCall_tooltip: "Videollamada",
    accessibility_startCall_ariaLabel: "Llamar",
    videoCallDisabled_tooltip: "No puedes realizar videollamadas con {agentName}",
    startCall_tooltip: "Llamada",
    accessibility_startGroupCall_ariaLabel: "Llamada grupal",
    callDisabled_tooltip: "No puedes llamar a {agentName}",
    startGroupCall_tooltip: "Llamar al grupo",
    turnOffChatNotifications_tooltip: "Desactivar las notificaciones de chat",
    turnOnChatNotifications_tooltip: "Activar las notificaciones de chat",
    giveFeedback_tooltip: "Enviar comentarios",
    giveFeedback_subject: "Comentarios sobre Skype en la Web",
    giveFeedback_body: "Si tiene algún problema o quiere enviar comentarios al equipo de Skype, indíquenoslo a continuación.",
    giveFeedback_button_label: "Comentarios",

    conversationHeader_heading_ariaLabel: "Conversación con {topic}.",
    groupProfile_spacesLink_ariaLabel: "Vínculo a este chat de grupo: {spacesUrl}",

    conversation_header_topic_default: "Sin título",
    conversation_header_topic_untitled_conversation: "Conversación sin título",
    conversation_header_topic_people_chatting: "{count} persona está disponible",
    conversation_header_topic_people_chatting_few: "{count} personas están disponibles",
    conversation_header_topic_people_chatting_many: "{count} personas están disponibles",

    message_text_presenceActive: "Activo",
    message_text_presenceMobile: "En el móvil",
    message_text_presenceAway: "Ausente",
    message_text_presenceBusy: "Ocupado",
    message_text_presenceDoNotDisturb: "No molestar",
    message_text_presenceUnknown: "Estado desconocido",

    message_text_activity_inAMeeting: "En una reunión",
    message_text_activity_urgentInterruptionsOnly: "Solo interrupciones urgentes",
    message_text_activity_onThePhone: "Al teléfono",
    message_text_activity_inAConference: "En una conferencia",
    message_text_activity_offWork: "Ausente del trabajo",
    message_text_activity_outOfOffice: "Fuera de la oficina",
    message_text_activity_presenting: "Presentando",

    expressionPicker_prevPage: "Pestañas anteriores",
    expressionPicker_nextPage: "Pestañas siguientes",
    expressionPicker_selected_item_title: "{itemTitle} seleccionado.",
    expressionPicker_mruTab_title: "Usados más recientemente",
    expressionPicker_mruTab_ariaLabel: "Usados más recientemente",
    expressionPicker_mruTab_emptyText: "Los elementos usados recientemente se mostrarán aquí.",
    expressionPicker_tab_emptyText: "Esta pestaña está vacía",
    expressionPicker_bingTab_title: "Bing",
    expressionPicker_bingTab_ariaLabel: "Buscar imágenes en Bing",
    expressionPicker_bingTab_emptyText: "Aquí aparecen los resultados de Bing",
    expressionPicker_bingTab_loadingText: "Cargando...",
    expressionPicker_bingTab_errorText: "Ha ocurrido un error. Inténtelo de nuevo más tarde",
    expressionPicker_bingPack_title: "Resultados de la búsqueda de Bing",
    expressionPicker_bingPack_ariaLabel: "Resultados de la búsqueda de Bing",
    expressionPicker_bingGifsPack_title: "GIF populares de Bing",
    expressionPicker_bingMemePack_title: "Memes populares de Bing",
    expressionPicker_bingGifsPack_ariaLabel: "GIF populares de Bing",
    expressionPicker_bingMemePack_ariaLabel: "Memes populares de Bing",

    expressionPicker_giphyImgTab_title: "Buscar Giphy",
    expressionPicker_giphyImgTab_ariaLabel: "Buscar GIF animados. Con tecnología de Giphy",
    expressionPicker_giphyImgTab_emptyText: "Los resultados de Giphy aparecen aquí",
    expressionPicker_giphyImgTab_loadingText: "Cargando...",
    expressionPicker_giphyImgTab_errorText: "Se ha producido un error. Inténtelo de nuevo más tarde",
    expressionPicker_giphyImgTab_terms: "Condiciones de Uso",
    expressionPicker_giphyImgPack_title: "Resultados de la búsqueda Giphy",
    expressionPicker_giphyImgPack_ariaLabel: "Resultados de la búsqueda Giphy",

    input_placeholder_searchPESItems: "Buscar elementos...",
    input_searchPESItems_ariaLabel: "Busque elementos. Escriba una palabra clave",
    expressionPicker_localSearchTab_title: "Buscar",
    expressionPicker_localSearchTab_emptyText: "Busque emoticonos y Mojis.",
    expressionPicker_localSearchPack_title: "Sugerencias rápidas",
    expressionPicker_localSearchPack_ariaLabel: "Sugerencias rápidas",

    expressionPicker_mruEmoticonPack_title: "Emoticonos",
    expressionPicker_mruEmoticonPack_ariaLabel: "Emoticonos",
    expressionPicker_mruMojiPack_title: "Mojis",
    expressionPicker_mruMojiPack_ariaLabel: "Mojis",
    expressionPicker_store_title: "Almacén de expresiones de Skype",
    expressionPicker_store_free: "Gratis",
    expressionPicker_storeTab_title: "Tienda",
    expressionPicker_store_Downloaded: "Descargado",
    expressionPicker_store_Downloading: "Descargando...",
    expressionPicker_store_removeTab: "Quitar",
    input_placeholder_searchPESStore: "Buscar",
    accessibility_open_picker: "Menú expandido",
    accessibility_close_picker: "Menú contraído",

    pes_moji_error_text: "El Moji no se ha podido cargar. Inténtelo de nuevo más tarde.",

    // Skype Polls feature related strings
    poll_designer_question_placeholder: "Hacer una pregunta...",
    poll_designer_answer_placeholder: "Agregar opción...",
    poll_message_question_header: "Sondeo: {pollQuestion}",
    poll_message_goto_text: "Para votar, vaya a {fallbackLink}.",
    poll_message_people_voted: "Votaron {count} personas",
    poll_sticky_message_new_poll: "Sondeo en curso de {author}: ",
    poll_sticky_message_me_voted: "Mi voto: {answerText}",
    poll_sticky_message_me_not_voted: "Haz clic aquí para votar",
    poll_fallback_link_text: "Skype para Web",
    poll_list_title: "{count} votos",

    presence_lastseen_moments: "Visto por última vez hace un momento",
    presence_lastseen_minutes: "Visto por última vez hace {number} min",
    presence_lastseen_hours: "Visto por última vez hace {number} h",
    presence_lastseen_days: "Visto por última vez hace {number} día(s)",

    presence_lastseen_date_short: "Visto por última vez: {shortdate}",
    presence_lastseen_date_full: "Visto por última vez: {fulldate}",

    guest_user_displayname: "{displayName} (invitado)",
    pes_featured_title: "Destacado",
    //Call to action for the moji play button
    pes_moji_playbutton_label: "Haz clic aquí para reproducir",

    label_jumpToConversation: "Ir a la conversación",

    share_on_skype_dialog_title: "Compartir en Skype",
    share_on_skype_share_button: "Compartir",
    share_on_skype_alt_text_button: "Compartir en Skype",

    share_on_skype_message_prompt: "Incluya un mensaje acerca de esto...",
    share_on_skype_picker_prompt: "Busca o selecciona...",
    share_on_skype_status_sending: "Enviando...",
    share_on_skype_status_sent: "Enviado",

    share_on_skype_signed_in_as: "Sesión iniciada como {displayName}",
    share_on_skype_my_account: "Mi cuenta",
    share_on_skype_sign_out: "Cerrar sesión",

    file_transfer_file_shared: "compartió un archivo",
    file_transfer_share_file: "Compartir un archivo",
    file_transfer_send_photos_and_files: "Enviar fotos y archivos",
    file_transfer_download_button_title: "Descargar archivo {filename}",
    file_transfer_download_dialog_confirm_button_title: "Aceptar",
    file_transfer_download_unsafe_file_dialog_title: "Advertencia: Puede que este archivo no sea seguro para su equipo o dispositivo.",
    file_transfer_download_unsafe_file_dialog_text: "¿Desea aceptar el archivo {filename} de {author}?",
    file_transfer_download_safe_file_dialog_title: "Acepta archivos solo de personas de confianza.",
    file_transfer_download_safe_file_dialog_text: "¿Desea aceptar el archivo {filename} de {author}?",
    file_transfer_download_dialog_do_not_ask_checkbox: "No volver a preguntar",
    file_transfer_upload_state: "{uploaded} de {size}",
    file_transfer_upload_completed: "El archivo {filename} se cargó correctamente",
    file_transfer_upload_failed: "No se puede cargar el archivo",
    file_transfer_upload_canceled: "Se canceló la carga",
    file_transfer_upload_cancel: "Cancelar la carga",
    file_transfer_upload_too_large_warning: "No se ha enviado: el archivo es más grande de 100 MB. <a href='http://go.skype.com/Cloud.File.Upload' target='_blank'>Más información</a>",
    file_transfer_upload_starting: "Iniciando la carga",
    file_transfer_upload_not_supported: "El uso compartido de archivos no es compatible con Skype para Web",

    notificationsPage_text_menuLink: "Notificaciones",
    remove_conversation_confirmation_text: "Todos los mensajes de la conversación se eliminarán y quitarán tanto de la barra lateral como del historial.",
    remove_conversation_confirmation_text_4b: "Saldrá de esta conversación y se eliminará de la barra lateral.",
    remove_conversation_confirmation_title: "¿Está seguro de querer eliminar el chat?",
    remove_conversation_confirmation_title_4b: "¿Está seguro de querer cerrar esta conversación?",
    accessibility_remove_conversation_confirmation: "Conversación eliminada",
    leave_conversation_confirmation_text: "Esta acción no se puede deshacer.",
    leave_conversation_confirmation_text_4b: "No recibirá más notificaciones de esta conversación. Puede volver a unirse a ella enviando un mensaje nuevo.",
    leave_conversation_confirmation_title: "¿Está seguro de que desea salir de \"{topic}\"?",
    leave_conversation_confirmation_title_4b: "¿Confirma que desea salir de la conversación?",

    contact_information_already_contact: "Ya es un contacto",
    contact_information_add_to_contacts: "Añadir a contactos",
    mediaBar_sendContacts_label: "Enviar contactos...",
    contactPicker_sendContacts_title: "Enviar contactos",
    contactPicker_sendContacts_OKBUtton: "Enviar",
    chat_contactSent_label: "Contacto enviado",
    chat_contactSent_iconLabel: "Enviado",
    mention_notification_title: "{participant} le mencionó en {chat}",
    contextMenu_picture_viewAction: "Ver",
    contextMenu_picture_commentAction: "Comentario",
    contextMenu_picture_downloadAction: "Descargar",
    contextMenu_text_discussAction: "Debatir",

    send_contacts_action_title: "Enviar contactos",
    send_contacts_action_text: "Agregue los contactos que desee enviar",

    invite_free_overlay_greeting: "Saluda a",
    invite_free_bubble_contact: "Escribe un mensaje aquí",
    invite_free_bubble_non_contact: "Escribe un mensaje aquí y espera una respuesta.",
    invite_free_textarea_waiting_for_reply: "Esperando una respuesta...",
    invite_free_message_received: "<strong>{displayName}</strong> le envió un mensaje",
    invite_free_message_received_location: "<strong>{displayName}</strong> le envió un mensaje desde {location}",
    invite_free_block_person: "Bloquear a esta persona",
    invite_free_respond_request: "Escriba cualquier mensaje para aceptar a este contacto",

    me_pluginLinkText: "Descargar complemento de Skype",
    me_accountLinkText: "Cuenta",
    me_accountSignOutLinkText: "Cerrar sesión",
    me_pendingPresence: "Obteniendo estado...",

    me_avatar_uploadProfilePictureText: "Cargar una imagen de perfil",
    me_avatar_uploadProfilePictureAriaLabel: "Cargar avatar",

    me_edit_activity_message: "Editar mensaje de actividad",
    me_activity_message_title: "Actividad actual",
    me_input_text_activity_message_placeholder: "Cambiar mensaje de actividad",
    me_edit_activity_message_confirm: "Guardar cambios",
    me_edit_activity_message_cancel: "Cancelar cambios",

    accessibility_me_changePresenceStatusAriaLabel: "Cambiar su estado en línea (actualmente {currentStatus})",

    message_sent_status: "Enviado",
    message_sending_status: "Enviando",
    message_delivered_status: "Entregado",
    message_read_status: "Leído",
    message_failed_status: "Error",

    message_edited_success: "Mensaje editado",
    message_removed_success: "Mensaje quitado",

    credit_balance_text: "Su crédito de Skype",
    credit_purchase_link_text: "Agregar crédito de Skype",
    subscription_entitlement_text: "Suscripciones",
    subscription_purchase_link_text: "Obtener una suscripción",
    no_subscriptions_text: "No tiene suscripciones",
    subscriptions_text_one: "Tiene {count} suscripción",
    subscriptions_text_many: "Tiene {count} suscripciones",
    pstn_emergency_notice_text: "Skype para Web (Beta) no sustituye al servicio telefónico y no puede usarse para llamadas de emergencia.",
    pstn_insufficient_funds: "Error de llamada: necesita {credit} o {subscription} para llamar a teléfonos fijos y móviles desde Skype.",
    pstn_insufficient_funds_credit: "Crédito de Skype",
    pstn_insufficient_funds_subscription: "una suscripción",
    pstn_invalid_number: "El número que ha marcado no es válido.",
    pstn_invalid_number_return_link: "Vuelva a Llamar a teléfonos y vuelva a intentarlo.",
    pstn_forbidden_number: "No se puede llamar al número que ha marcado con Skype.",
    pstn_insufficient_funds_group: "El participante con el número de teléfono {phoneNumber} no se pudo unir a la llamada. Necesita {credit} o {subscription} para agregarlo a la llamada.",
    pstn_insufficient_funds_group_name: "El participante {displayName} ({phoneNumber}) no se pudo unir a la llamada. Necesita {credit} o {subscription} para agregarlo a la llamada.",
    pstn_invalid_number_group: "El participante con el número de teléfono {phoneNumber} no se pudo unir a la llamada porque el número no es válido.",
    pstn_invalid_number_group_name: "El participante {displayName} ({phoneNumber}) no se pudo unir a la llamada porque el número no es válido.",
    pstn_forbidden_number_group: "El participante con el número de teléfono {phoneNumber} no se pudo unir a la llamada. No se puede contactar con el número mediante Skype.",
    pstn_forbidden_number_group_name: "El participante {displayName} ({phoneNumber}) no se pudo unir a la llamada. No se puede conectar con el número mediante Skype.",

    hearts_bubble_title: "A quién le gusta esto",
    hearts_bubble_meliked: "Usted",
    hearts_loved_by: "{list}",
    hearts_loved_by_count: "Le encanta a {count}",
    hearts_loved_by_others: "Le encanta a {list} y a <span>{count}&nbsp;personas más</span>",

    hearts_list_title: "Le gusta a ({count})",
    hearts_me_text: "Usted",
    hearts_like_byMeOnly: "Le gusta esto",
    hearts_like_byOne: "A {participantName} le gusta esto",
    hearts_like_byFew: "A {participantFirst}{list} y a {participantLast} les gusta esto",
    hearts_like_byMany: "A {participantlist} y a <span>otros&nbsp;{count}</span> les gusta esto",
    hearts_notification_messageGroup: "A {participantName} le gusta su mensaje {messageText}",
    hearts_notification_messageConv: "le gusta su mensaje {messageText}",
    hearts_notification_photoGroup: "A {participantName} le gusta su foto",
    hearts_notification_photoConv: "le gusta su foto",
    hearts_notification_fileGroup: "A {participantName} le gusta su archivo",
    hearts_notification_fileConv: "le gusta su archivo",
    hearts_notification_documentGroup: "A {participantName} le gusta su documento",
    hearts_notification_documentConv: "le gusta su documento",
    hearts_notification_videoMessageGroup: "A {participantName} le gusta su mensaje de vídeo",
    hearts_notification_videoMessageConv: "le gusta su mensaje de vídeo",
    hearts_notification_urlGroup: "A {participantName} le gusta su URL",
    hearts_notification_urlConv: "le gusta su URL",
    hearts_notification_youTubeGroup: "A {participantName} le gusta su vídeo de YouTube",
    hearts_notification_youTubeConv: "le gusta su vídeo de YouTube",

    hearts_accessibility_like: "Indicar que le gusta este mensaje",
    hearts_accessibility_unlike: "Indicar que no le gusta este mensaje",

    hearts_toast_message: "nuevo",
    hearts_toast_title: "haga clic para ir al mensaje que le gusta",
    me_notificationsOn: "Notificaciones activadas",
    me_notificationsOff: "Notificaciones desactivadas",

    education_bubble_search: "Para hablar o chatear con otras personas, búsquelas por su correo electrónico o nombre de usuario.",
    education_bubble_search_4b: "Haga clic en este botón para buscar a personas con las que chatear.",
    education_bubble_search_title_4b: "Buscar un contacto",
    education_bubble_call: "Seleccione el botón de cámara para iniciar una videollamada.",
    education_bubble_chat: "Elija un contacto para iniciar una llamada o un chat.",
    education_bubble_chat_4b: "Haga clic en un contacto para enviarle un mensaje.",
    education_bubble_chat_title_4b: "Enviar un MI",
    education_bubble_gotit_button_4b: "Entendido",
    education_bubble_schedule_call_1: "Programe su siguiente llamada con {name} aquí.",
    education_bubble_schedule_call_1_group: "Mantenga el contacto, programe aquí su siguiente llamada.",

    schedule_call_new_conversation_topic: "Llamada de Skype",
    schedule_call_subject_text: "Llamada de Skype con {topic}",

    welcomeDialog_header: "Skype para Web (Beta)",
    welcomeDialog_getInTouch: "Póngase en contacto con sus amigos y familiares directamente desde el explorador.",
    welcomeDialog_sendIM: "Enviar mensajes instantáneos",
    welcomeDialog_makeCalls: "Realizar llamadas con Skype",
    welcomeDialog_makeVideoCalls: "Hacer videollamadas",
    welcomeDialog_getStarted_button: "Introducción",
    welcomeDialog_notForEmergencyCalls: "Skype para Web (Beta) no sustituye al servicio telefónico y no puede usarse para llamadas de emergencia.",
    welcomeDialog_cookiesConsent: "El uso de este sitio significa que está de acuerdo con que usemos cookies para realizar análisis y para poder mostrar contenido y anuncios personalizados.",
    welcomeDialog_readMore: "Leer más información sobre cookies",

    modal_scheduleCall_getting_ready_label: "Preparando la llamada…",
    modal_scheduleCall_ready_label: "La llamada está preparada para su programación.",
    modal_scheduleCall_create_event_button: "Crear evento",
    modal_scheduleCall_close_button: "Cerrar",

    cqf_title: "¿Qué calificación le daría a la calidad de esta llamada?",
    cqf_audio_title: "Infórmenos de cualquier problema de audio que haya experimentado. Usaremos los comentarios para mejorar Skype.",
    cqf_video_title: "Infórmenos de cualquier problema de audio o video que haya experimentado. Usaremos los comentarios para mejorar Skype.",
    cqf_audio_tokens_title: "Audio",
    cqf_video_tokens_title: "Video",
    cqf_audio_nolocal: "No escuchaba nada",
    cqf_audio_noremote: "La otra persona no escuchaba nada",
    cqf_audio_quality_echo: "Se escuchaba eco en la llamada",
    cqf_audio_quality_noise: "Se escuchaba ruido en la llamada",
    cqf_audio_quality_volume: "El volumen era bajo",
    cqf_audio_dropped: "La llamada terminó de forma inesperada",
    cqf_audio_quality_distorted: "La voz no era natural o sonaba distorsionada",
    cqf_audio_quality_delay: "Nos interrumpimos el uno al otro",
    cqf_audio_other: "Otro, especifique",
    cqf_audio_quality_dialpad: "No funcionaron los tonos del teclado de marcado",
    cqf_video_nolocal: "No veía nada",
    cqf_video_noremote: "La otra persona no podía ver mi vídeo",
    cqf_video_quality_poor: "La calidad de imagen no era buena",
    cqf_video_quality_freezing: "El vídeo se congelaba",
    cqf_video_dropped: "El vídeo se detuvo de forma inesperada",
    cqf_video_quality_dark: "La otra persona estaba muy oscura",
    cqf_video_quality_sync: "Mala sincronización entre vídeo y audio",
    cqf_video_other: "Otro, especifique",
    cqf_thanks_title: "Gracias por sus comentarios.",

    cqf_accessibility_cancel_btn: "Cancelar",
    cqf_accessibility_submit_btn: "Enviar comentarios",
    cqf_accessibility_oneStar_ariaLabel: "Muy mala",
    cqf_accessibility_twoStars_ariaLabel: "Mala",
    cqf_accessibility_threeStars_ariaLabel: "Regular",
    cqf_accessibility_fourStars_ariaLabel: "De buena calidad",
    cqf_accessibility_fiveStars_ariaLabel: "Excelente",

    favorites_recents_category_name: "Favoritos",
    favorites_add_to_favorite: "Agregar a Favoritos",
    favorites_remove_from_favorite: "Quitar de Favoritos",

    welcome_im_display_name: "Enviar MI en Outlook",
    welcome_im_toast_message: "Ahora puede enviar MI desde Outlook.\r\n\r\n",
    welcome_im_first_message: "Escriba un mensaje a continuación y pulse Entrar para probarlo.\r\n\r\nPara que sea más divertido, agregue algunos :) B-) :D",
    welcome_im_reply_message: "(clap) Fantástico. Ahora siga adelante y envíe un mensaje.",

    unreadConversationsReminder: "Tiene {count} conversación sin leer",
    unreadConversationsReminder_few: "Tiene {count} conversaciones sin leer",
    unreadConversationsReminder_many: "Tiene {count} conversaciones sin leer",

    unreadMessageFromPersonAndOthersReminder: "Tiene mensajes sin leer de {name} y {count} más",
    unreadMessageFromPersonAndOthersReminder_few: "Tiene mensajes sin leer de {name} y {count} más",
    unreadMessageFromPersonAndOthersReminder_many: "Tiene mensajes sin leer de {name} y {count} más",

    unreadMessageFromPersonReminder: "Tiene mensajes sin leer de {name}",

    unreadMessageInGroupAndOthersReminder: "Tiene mensajes sin leer de {topic} y {count} más",
    unreadMessageInGroupAndOthersReminder_few: "Tiene mensajes sin leer de {topic} y {count} más",
    unreadMessageInGroupAndOthersReminder_many: "Tiene mensajes sin leer de {topic} y {count} más",

    unreadMessageInGroupReminder: "Tiene mensajes sin leer de {topic}"
});
